config/routes.rb
Rails.application.routes.draw do
  resources :events do
    member do
      put :attendance_status_check
    end
  end
  resources :users, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :show, :destroy]
  resources :authorizations, :only => [:create, :blank, :failure, :destroy]
  match '/auth/:provider/callback' => 'authorizations#create',via: [:get, :post]
  match '/auth/failure' => 'authorizations#failure', via: [:get, :post]
  match '/auth/:provider' => 'authorizations#blank', via: [:get, :post]

  root 'events#index'

  get 'info/about' =>"info#about"
  get 'info/contact' =>"info#contact"
  get 'info/my_events' =>"info#my_events"
  get 'info/privacy_policy' => "info#privacy_policy"

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :attendances
  has_many :users, through: :attendances
  has_one :location, dependent: :destroy
  belongs_to :user
  validates_presence_of :name,:organizer,:price,:address, :city, :state, :event_type,:dance_style, :description, :url, :facebook_url
  validates_uniqueness_of :name, :case_sensitive => false, :message => "This event seems to exist already..."
  validate :date_cannot_be_in_the_past
  validates :price, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }, :numericality => {:greater_than => -1}
  attachment :event_image
  validates_format_of :url, :facebook_url, :with => /\Ahttp(|s):\/\//
  before_validation :add_http

  def date_cannot_be_in_the_past
    errors.add(:date, "Events cannot be made for the past") if
      !date.blank? and date < Date.today
    errors.add(:date, "Events must have a date") if
      date == nil
  end

  def add_http
    unless self.url =~ /\Ahttp(|s):\/\//
      self.url = "http://" + self.url
    end
    unless self.facebook_url =~ /\Ahttp(|s):\/\//
      self.facebook_url = "http://" + self.facebook_url
    end
  end

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end

  after_save do |event|
    event.location = Location.new
    event.location.address = event.address + " " + event.city + "," + event.state
    event.location.save!
  end




end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  filter_access_to :all
  filter_access_to :show, :edit, :update, :destroy, :attendance_status_check, :attribute_check => true

  def index
    @user = current_user
    @events = Event.all.order("date ASC")
    @events = @events.search(params[:search]).paginate(:page => params[:page], :per_page => 8)
      if @events.size.zero?
        flash[:notice]="No match was found."

      end
    @mapevents = Event.all
    @hash = Gmaps4rails.build_markers(@mapevents) do |event, marker|
      marker.lat event.location.latitude
      marker.lng event.location.longitude
    end
  end

  def new
    @user = current_user
    @event=@user.events.build
  end

  def create
    @event=Event.new(event_params)
    @event.user = current_user
    if @event.save
      flash[:notice]="You've added a new event!"
      @event.users << current_user
      redirect_to root_url
    else
      flash[:notice]="Looks like there were some errors. Let's double check."
      render :new
    end
  end

  def show
    @user = current_user
    @event=Event.find(params[:id])
    @events=Event.all
    @location=@event.address
    @hash = Gmaps4rails.build_markers(@event) do |event, marker|
      marker.lat event.location.latitude
      marker.lng event.location.longitude
    end
  end

  def attendance_status_check
    @event = Event.find(params[:id])
    if current_user.attending?(@event) ==false
      @event.users << current_user
      redirect_to :back
    else
      @event.users.delete(current_user)
      redirect_to :back
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to :back
    else
      render "edit"
    end
  end

  def destroy
    @event=current_user.events.find(params[:id])
    @event.destroy
    redirect_to root_url
  end

private

  def event_params
    params.require(:event).permit(:name,:organizer,:date,:price,:address,:city,:state,:event_type,:dance_style,:event_image,:description,:url, :facebook_url)
  end


end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event_data_form.html.haml
= bootstrap_form_for(@event) do |f|
  .col-xs-8
    .field
      = f.text_field :name, placeholder:"Event Name - Displays only 30 characters on main page"
    .col-xs-6
      .field
        = f.text_field :organizer
    .col-xs-6
      .field
        = f.text_field :address, placeholder: "Street Address"
    .col-xs-6
      .field
        = f.text_field :city, placeholder: "City"
    .col-xs-6
      .field
        = f.text_field :state, placeholder: "State"
    .col-xs-6
      .field
        = f.date_field :date
    .col-xs-6
      .field
        = f.text_field :price, placeholder: "$ Dollars"
    .col-xs-6
      .field
        = f.select :event_type, ["Workshop","Exchange","Evening Dance","Dance Camp","Special Event"], :include_blank => 'Select Type'
    .col-xs-6
      .field
        = f.select :dance_style, ["Lindy Hop","Charleston","Shag","Blues","Boogie Woogie","Balboa", "Other"], :include_blank => 'Select Type'
    .field
      = f.text_area :description, placeholder: "Tell us a bit about this event!"
    .col-xs-6
      .field
        = f.text_field :url, placeholder: "Website for registration and info"
    .col-xs-6
      .field
        = f.text_field :facebook_url, placeholder: "Facebook Event Page"
  .event-sidebar.col-xs-4
    %h3 Upload an Event Image
    %h5{:style => "font-style:italic;"} Pro-tip: square .png files with no background work best!
    #event_image_thumbnail
      = f.attachment_field :event_image
    %br/
    #preview
      - if @event.event_image
        = image_tag attachment_url(@event, :event_image), width: 300
  .col-xs-9
  .col-xs-2
    .event-submit.actions
      = f.submit "Submit", class: "btn btn-standard btn-lg"

app/views/events/_panel_tile.html.haml
-@events.each_slice(4) do |four|
  .row
    - four.each do |event|
      .col-xs-3.event-tabs
        .panel.panel-default
          <!--Heading-->
          .panel-heading.panel-title
            .event-tab
              = link_to truncate(event.name, :length => 30), event
              %br/
              - if event.user == current_user && current_user != nil
                .glyphicon.glyphicon-flag
          <!--Body-->
          .panel-body.main
            = event.city
            = event.state
            %h4.event-date
              = event.date.strftime("%b %d")
            %p
              = event.date.strftime("%Y")
            = event.dance_style
            = event.event_type
          <!--Bottom-->
          .panel-heading.panel-bottom
            - if event.event_image
              .footer-with-icon
                = image_tag attachment_url(event, :event_image), class: "img-responsive event-image-thumbnail"
            - if current_user
              = link_to attendance_status_check_event_path(event), method: :put do
                - if current_user.attending?(event) == true
                  .going
                    .glyphicon.glyphicon-ok-sign
                - else
                  .not-going
                    .glyphicon.glyphicon-remove
#pagination
  = will_paginate @events

app/views/events/_regional_events.html.haml
- if @event.location.nearbys(200)
  .section-header
    %h3.title-section Other Regional Events
  .container
    %ul
    - @event.location.nearbys(200).take(6).each do |single_event|
      #event-tabs.col-xs-2
        .panel.panel-default
          / Heading
          #panel-title.panel-heading
            %h4.event-tab
              .row
                = link_to truncate(single_event.event.name, :length => 30), single_event.event
          / Body
          .panel-body.main
            - if single_event.distance.round(0) <= 20.0
              Also here in town!
            - else
              = single_event.distance.round(0)
              miles away
            %br
            - if single_event.event.city && single_event.event.state
              in #{single_event.event.city}, #{single_event.event.state}
            %br
            %h4.event-date
              = single_event.event.date.strftime("%b %d")
            %p
              = single_event.event.date.strftime("%Y")
            = single_event.event.dance_style
            = single_event.event.event_type
          / Bottom
          .panel-bottom.panel-heading
            - if single_event.event.event_image
              .footer-with-icon
                = image_tag attachment_url(single_event.event, :event_image), class: "img-responsive event-image-thumbnail"
            - if @user
              = link_to attendance_status_check_event_path(single_event.event), method: :put do
                - if @user.attending?(single_event.event)
                  .going
                    .glyphicon.glyphicon-ok-sign
                - else
                  .not-going
                    .glyphicon.glyphicon-remove

app/views/events/edit.html.haml
.section-header
  %h1.title-section Edit - #{@event.name}
.container
  = render "event_data_form"
  %br/

app/views/events/index.html.haml
#title-image
  %br/
  %h1.landing-page-text
    All The Swing Dancing!
.container
  .col-xs-8
    .about-info
      %hr
      Find All the Swing Dancing in one place
    .p{:style => "text-align: center; font-size: 18px;"}
      Welcome to the user-driven dance event posting site
    .p{:style => "text-align: center; font-size: 18px;"}
      keeping all your events in one handy location.
    .p{:style => "text-align: center; font-size: 18px; font-weight: 700;"}
      Always know when the dancing is happening!
      %hr
  .col-xs-4
    = image_tag("alltheswingdancing2x500.png", class: "img-responsive")
.section-header
  .container
    .row
      %h1.title-section All the Dance Events

.container
  .col-xs-3
    .search-title
      Search by Event Name
      = bootstrap_form_for events_path, :method => 'get' do
        = text_field_tag :search, params[:search]
        = submit_tag "Search", :name => nil
    .advertising-space
      This will be a rotating advert for events!
    .advertising-space
      This will be a rotating advert for events!

    / ADVERT SPACE HERE
  .col-xs-9
    = render partial: "panel_tile"

  / Resposive maps via GOOGLE
.section-header
  %h1.title-section
    All Event Locations
.container
  %div{:style => "width: 400px;"}
    #map{:style => "width: 950px; height: 400px;"}
  :javascript
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(#{raw @hash.to_json});
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });
  / END

app/views/events/new.html.haml
.section-header
  %h1.title-section Add an Event!
.container
  = render "event_data_form"
  %br/

app/views/events/show.html.haml
/ Event Title
.container
  .row
    .col-xs-10
      %h1#event-title= @event.name
      .owner-options
        .row
          .col-xs-3.info-points-data
            - if @event.user != nil
              Added by:
              = @event.user.username
            %br/
            - if permitted_to?(:edit, @event)
              %i.glyphicon.glyphicon-flag
              Owner Options:
              = link_to edit_event_path(@event) do
                %i.glyphicon.glyphicon-cog Edit
            - if permitted_to?(:destroy, @event)
              = link_to event_path(@event), method: :delete do
                %i.glyphicon.glyphicon-trash Delete
      / Event overview heading
      %hr
        .col-xs-3
          .info-points Event:
          .info-points-data
            = @event.dance_style
            = @event.event_type
        .col-xs-3
          - if number_to_currency(@event.price) == "$0.00"
            .info-points Price:
            .info-points-data Free!
          - else
            .info-points Price:
            .info-points-data= number_to_currency(@event.price)
        .col-xs-3
          .info-points Location:
          .info-points-data= @event.address
        .col-xs-3
          .info-points Host:
          .info-points-data= @event.organizer
    / Mini-Panel
    .col-xs-2
      .panel.panel-default.mini-panel
        .panel-heading
        .panel-body
          .event-date
            = @event.date.strftime("%b %d")
        .panel-bottom.panel-heading.mini-panel-bottom
          - if @user
            .panel-heading
              Status:
              = link_to attendance_status_check_event_path(@event), method: :put do
                - if current_user.attending?(@event) == true
                  .going
                    .glyphicon.glyphicon-ok-sign
                - else
                  .not-going
                    .glyphicon.glyphicon-remove
  / Event Body
  .row
    %hr
    .col-xs-8
      .event-description-body
        %p= @event.description
    .col-xs-4
      .event-description-sidebar
        = image_tag attachment_url(@event, :event_image), class: "img-responsive", id: "full-event-image"
  .row
    .container
      .facebook-link-to-event
        = link_to @event.facebook_url, :target => "_blank" do
          = image_tag("facebook_blu.png")
      .external-event-site-button
        = button_to "#{@event.name} website", @event.url, :target => "_blank", class: "btn btn-standard btn-lg"

  %br
    / Resposive maps via GOOGLE
  .section-header
    %h3.title-section Event Location Map
  %div{:style => "width: 400px;"}
    #map{:style => "width: 950px; height: 400px;"}
  :javascript
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(#{raw @hash.to_json});
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      handler.getMap().setZoom(14);
    });
  / END
= render partial: "regional_events"